[package]
name = "quarxcloud"
version = "0.1.0"
edition = "2021"

[lib]
name = "quarxcloud"
path = "src/lib.rs"

[dependencies]
quarxtor-core = { path = "../core-rs" }
quarxnet      = { path = "../quarxnet" }
